ABC:
  VERSION: 3.3.0
BROKING_DETAILS: { }
CANDLE:
  CANDLE_INTERVAL: minute
EXIT:
  EXIT_INTRADAY_ORDERS_ON_STOP: true
  EXIT_TPLUS0_DELIVERY_ORDERS_ON_STOP: false
  EXIT_TPLUS1_DELIVERY_ORDERS_ON_STOP: false
  EXIT_TPLUS2_DELIVERY_ORDERS_ON_STOP: false
FUNDS:
  CREDIT_EXPOSURE_FACTOR: 1
  INITIAL_FUNDS_VIRTUAL: 1000000000
MISC:
  CROSSOVER_ACCURACY_DECIMALS: 2
  MAX_ORDERS_COUNT: 100
RESUME:
  AUTO_ADD_INSTRUMENTS_BUCKET_FROM_HOLDINGS_TPLUS1: false
  AUTO_ADD_INSTRUMENTS_BUCKET_FROM_HOLDINGS_TPLUS2: false
  AUTO_ADD_INSTRUMENTS_BUCKET_FROM_POSITIONS: false
  RESUME_HOLDINGS_TPLUS1_ON_START: false
  RESUME_HOLDINGS_TPLUS2_ON_START: false
  RESUME_POSITIONS_ON_START: false
RISK_MANAGEMENT:
  PNL_SCAN_FREQUENCY: 30
  PROFIT_DESIRED: null
  RISK_APPETITE: null
STRATEGY:
  INSTRUMENTS_BUCKET:
    - NSE_IDX:NIFTY BANK
  MODE: INTRADAY
  NAME: Strategy Options Short Straddle with SL
  NUMBER_OF_LOTS: 1
  PARAMETERS:
    START_TIME_HOURS: 9.0
    START_TIME_MINUTES: 17.0
    END_TIME_HOURS: 15.0
    END_TIME_MINUTES: 10.0
    FRESH_ORDER_MINUTES: 1.0
    NUMBER_OF_STRIKES_LEG_ONE: 0.0
    NUMBER_OF_STRIKES_LEG_TWO: 0.0
    STRIKE_DIRECTION_LEG_ONE: 1.0
    STRIKE_DIRECTION_LEG_TWO: 1.0
    STOPLOSS_PERCENTAGE_LEG_ONE: 20.0
    STOPLOSS_PERCENTAGE_LEG_TWO: 20.0
    INSTRUMENT_EXCHANGE_TOKEN: 1016.0
    INSTRUMENT_SEGMENT: 3.0
    LOWER_LIMIT_THRESHOLD: 100.0
    UPPER_LIMIT_THRESHOLD: 100.0
    PNL_ABSOLUTE: 1.0
    SMA_PERIOD: 1.0
    TRAILING_STOP_LOSS: -1000.0
    ABSOLUTE_STOP_LOSS: 500.0
    TRAILING_TYPE: 0.0
  SECURE: true
SYSTEM:
  TRADING_TYPE: BACKTESTING
  TRADING_START_TIME: 26-12-2023 09:16 +0530
  TRADING_END_TIME: 29-12-2023 15:15 +0530
