ABC:
  VERSION: 3.3.0
BROKING_DETAILS: { }
CANDLE:
  CANDLE_INTERVAL: 15 minutes
EXIT:
  EXIT_INTRADAY_ORDERS_ON_STOP: true
  EXIT_TPLUS0_DELIVERY_ORDERS_ON_STOP: false
  EXIT_TPLUS1_DELIVERY_ORDERS_ON_STOP: false
  EXIT_TPLUS2_DELIVERY_ORDERS_ON_STOP: false
FUNDS:
  CREDIT_EXPOSURE_FACTOR: 1
  INITIAL_FUNDS_VIRTUAL: 80000
  MINIMUM_CAPITAL_REQUIRED: 80000
MISC:
  CROSSOVER_ACCURACY_DECIMALS: 2
  MAX_ORDERS_COUNT: 100
RESUME:
  AUTO_ADD_INSTRUMENTS_BUCKET_FROM_HOLDINGS_TPLUS1: false
  AUTO_ADD_INSTRUMENTS_BUCKET_FROM_HOLDINGS_TPLUS2: false
  AUTO_ADD_INSTRUMENTS_BUCKET_FROM_POSITIONS: false
  RESUME_HOLDINGS_TPLUS1_ON_START: false
  RESUME_HOLDINGS_TPLUS2_ON_START: false
  RESUME_POSITIONS_ON_START: false
RISK_MANAGEMENT:
  PNL_SCAN_FREQUENCY: 30
  PROFIT_DESIRED: null
  RISK_APPETITE: null
STRATEGY:
  INSTRUMENTS_BUCKET:
    - NSE_IDX:NIFTY 50
  MODE: INTRADAY
  NAME: Strategy Options Long Call Diagonal Spread With TSL & Reentry
  NUMBER_OF_LOTS: 1
  PARAMETERS:
    FLAG_FETCH_INSTRUMENTS_FOR_EXPIRY_MONTHLY_CURRENT: 1
    FLAG_FETCH_INSTRUMENTS_FOR_EXPIRY_MONTHLY_NEXT: 1
    NUMBER_OF_OTM_STRIKES_SELL_LEG: 4
    STOPLOSS_PERCENTAGE: 5
    TRAILING_STOPLOSS_PERCENTAGE: 30
    RE_ENTRY_LIMIT: 3
  SECURE: true
SYSTEM:
  TRADING_TYPE: BACKTESTING
  TRADING_START_TIME: 11-03-2023 09:15 +0530
  TRADING_END_TIME: 17-03-2023 15:15 +0530

