ABC:
  VERSION: 3.3.0
BROKING_DETAILS: { }
CANDLE:
  CANDLE_INTERVAL: 60minutes
EXIT:
  EXIT_INTRADAY_ORDERS_ON_STOP: true
  EXIT_TPLUS0_DELIVERY_ORDERS_ON_STOP: false
  EXIT_TPLUS1_DELIVERY_ORDERS_ON_STOP: false
  EXIT_TPLUS2_DELIVERY_ORDERS_ON_STOP: false
FUNDS:
  CREDIT_EXPOSURE_FACTOR: 1
  INITIAL_FUNDS_VIRTUAL: 1000000000
MISC:
  CROSSOVER_ACCURACY_DECIMALS: 2
  CUSTOMER_SESSION_TOKEN: null
  MAX_ORDERS_COUNT: 100
RESUME:
  AUTO_ADD_INSTRUMENTS_BUCKET_FROM_HOLDINGS_TPLUS1: true
  AUTO_ADD_INSTRUMENTS_BUCKET_FROM_HOLDINGS_TPLUS2: true
  AUTO_ADD_INSTRUMENTS_BUCKET_FROM_POSITIONS: true
  RESUME_HOLDINGS_TPLUS1_ON_START: true
  RESUME_HOLDINGS_TPLUS2_ON_START: true
  RESUME_POSITIONS_ON_START: true
RISK_MANAGEMENT:
  PNL_SCAN_FREQUENCY: 30
  PROFIT_DESIRED: null
  RISK_APPETITE: null
STRATEGY:
  INSTRUMENTS_BUCKET:
    - NSE:ICICIBANK
  MODE: DELIVERY
  NAME: Inverse EMA Scalping Regular Order Delivery
  NUMBER_OF_LOTS: 2
  PARAMETERS:
    LARGER_TIME_PERIOD: 7.0
    SMALLER_TIME_PERIOD: 2.0
SYSTEM:
  TRADING_END_TIME: 28-02-2023 15:30 +0530
  TRADING_START_TIME: 01-01-2023 09:15 +0530
  TRADING_TYPE: BACKTESTING
