ABC:
  VERSION: 3.3.0
BROKING_DETAILS: { }
CANDLE:
  CANDLE_INTERVAL: 15minutes
EXIT:
  EXIT_INTRADAY_ORDERS_ON_STOP: true
  EXIT_TPLUS0_DELIVERY_ORDERS_ON_STOP: false
  EXIT_TPLUS1_DELIVERY_ORDERS_ON_STOP: false
  EXIT_TPLUS2_DELIVERY_ORDERS_ON_STOP: false
FUNDS:
  CREDIT_EXPOSURE_FACTOR: 1
  INITIAL_FUNDS_VIRTUAL: 1000000000
MISC:
  CROSSOVER_ACCURACY_DECIMALS: 2
  MAX_ORDERS_COUNT: 100
RESUME:
  AUTO_ADD_INSTRUMENTS_BUCKET_FROM_HOLDINGS_TPLUS1: true
  AUTO_ADD_INSTRUMENTS_BUCKET_FROM_HOLDINGS_TPLUS2: true
  AUTO_ADD_INSTRUMENTS_BUCKET_FROM_POSITIONS: true
  RESUME_HOLDINGS_TPLUS1_ON_START: true
  RESUME_HOLDINGS_TPLUS2_ON_START: true
  RESUME_POSITIONS_ON_START: true
RISK_MANAGEMENT:
  PNL_SCAN_FREQUENCY: 30
  PROFIT_DESIRED: null
  RISK_APPETITE: null
STRATEGY:
  INSTRUMENTS_BUCKET:
    - NSE:SBIN
  MODE: DELIVERY
  NAME: Strategy Aroon Crossover Delivery
  NUMBER_OF_LOTS: 5
  PARAMETERS:
    TIME_PERIOD: 12
SYSTEM:
  TRADING_TYPE: BACKTESTING
  TRADING_START_TIME: 01-01-2023 09:15 +0530
  TRADING_END_TIME: 31-03-2023 15:30 +0530


