ABC:
  VERSION: 3.3.0
AB_HISTDB_DETAILS:
  AB_HISTDB_HOST_NAME: localhost
  AB_HISTDB_HOST_PORT: 7777
BROKING_DETAILS: {}
CANDLE:
  CANDLE_INTERVAL: 60minutes
EXIT:
  EXIT_INTRADAY_ORDERS_ON_STOP: true
  EXIT_TPLUS0_DELIVERY_ORDERS_ON_STOP: false
  EXIT_TPLUS1_DELIVERY_ORDERS_ON_STOP: false
  EXIT_TPLUS2_DELIVERY_ORDERS_ON_STOP: false
FUNDS:
  CREDIT_EXPOSURE_FACTOR: 1
  INITIAL_FUNDS_VIRTUAL: 1000000000
MISC:
  CROSSOVER_ACCURACY_DECIMALS: 2
  CUSTOMER_SESSION_TOKEN: 0a0d85f07a2dec02af2c1879e5431555911c67ef
  MAX_ORDERS_COUNT: 100
RESUME:
  AUTO_ADD_INSTRUMENTS_BUCKET_FROM_HOLDINGS_TPLUS1: false
  AUTO_ADD_INSTRUMENTS_BUCKET_FROM_HOLDINGS_TPLUS2: false
  AUTO_ADD_INSTRUMENTS_BUCKET_FROM_POSITIONS: false
  RESUME_HOLDINGS_TPLUS1_ON_START: false
  RESUME_HOLDINGS_TPLUS2_ON_START: false
  RESUME_POSITIONS_ON_START: false
RISK_MANAGEMENT:
  PNL_SCAN_FREQUENCY: 30
  PROFIT_DESIRED: null
  RISK_APPETITE: null
STRATEGY:
  INSTRUMENTS_BUCKET:
  - NSE_IDX:NIFTY 50
  MODE: INTRADAY
  NAME: Options Bear Put Ladder
  NUMBER_OF_LOTS: 1
  PARAMETERS:
    FLAG_FETCH_INSTRUMENTS_FOR_EXPIRY_MONTHLY_CURRENT: 0.0
    FLAG_FETCH_INSTRUMENTS_FOR_EXPIRY_MONTHLY_NEXT: 0.0
    FLAG_FETCH_INSTRUMENTS_FOR_EXPIRY_WEEKLY_CURRENT: 1.0
    FLAG_FETCH_INSTRUMENTS_FOR_EXPIRY_WEEKLY_NEXT: 0.0
    LEG_ONE_NUMBER_OF_STRIKES: 0.0
    LEG_ONE_STRIKE_DIRECTION: 1.0
    LEG_ONE_TRADING_SYMBOL_SUFFIX: 2.0
    LEG_ONE_TRANSACTION_TYPE: 1.0
    LEG_THREE_NUMBER_OF_STRIKES: 2.0
    LEG_THREE_STRIKE_DIRECTION: 0.0
    LEG_THREE_TRADING_SYMBOL_SUFFIX: 2.0
    LEG_THREE_TRANSACTION_TYPE: 2.0
    LEG_TWO_NUMBER_OF_STRIKES: 2.0
    LEG_TWO_STRIKE_DIRECTION: 2.0
    LEG_TWO_TRADING_SYMBOL_SUFFIX: 2.0
    LEG_TWO_TRANSACTION_TYPE: 1.0
  SECURE: True
SYSTEM:
  TRADING_END_TIME: 31-10-2023 15:10 +0530
  TRADING_START_TIME: 01-06-2023 09:30 +0530
  TRADING_TYPE: BACKTESTING
