ABC:
  VERSION: 3.3.0
BROKING_DETAILS: { }
CANDLE:
  CANDLE_INTERVAL: 5minutes
EXIT:
  EXIT_INTRADAY_ORDERS_ON_STOP: true
  EXIT_TPLUS0_DELIVERY_ORDERS_ON_STOP: false
  EXIT_TPLUS1_DELIVERY_ORDERS_ON_STOP: false
  EXIT_TPLUS2_DELIVERY_ORDERS_ON_STOP: false
FUNDS:
  CREDIT_EXPOSURE_FACTOR: 1
  INITIAL_FUNDS_VIRTUAL: 1000000000
MISC:
  CROSSOVER_ACCURACY_DECIMALS: 2
  MAX_ORDERS_COUNT: 100
RESUME:
  AUTO_ADD_INSTRUMENTS_BUCKET_FROM_HOLDINGS_TPLUS1: false
  AUTO_ADD_INSTRUMENTS_BUCKET_FROM_HOLDINGS_TPLUS2: false
  AUTO_ADD_INSTRUMENTS_BUCKET_FROM_POSITIONS: false
  RESUME_HOLDINGS_TPLUS1_ON_START: false
  RESUME_HOLDINGS_TPLUS2_ON_START: false
  RESUME_POSITIONS_ON_START: false
RISK_MANAGEMENT:
  PNL_SCAN_FREQUENCY: 30
  PROFIT_DESIRED: null
  RISK_APPETITE: null
STRATEGY:
  INSTRUMENTS_BUCKET:
    - NSE:SBIN
  MODE: INTRADAY
  NAME: Strategy MACD Crossover Intraday
  NUMBER_OF_LOTS: 2
  PARAMETERS:
    TIMEPERIOD_FAST: 12.0
    TIMEPERIOD_SIGNAL: 9.0
    TIMEPERIOD_SLOW: 26.0
SYSTEM:
  TRADING_TYPE: BACKTESTING
  TRADING_START_TIME: 01-1-2023 09:15 +0530
  TRADING_END_TIME: 25-02-2023 15:30 +0530
