ABC:
  VERSION: 3.3.0
BROKING_DETAILS: { }
CANDLE:
  CANDLE_INTERVAL: 60minutes
EXIT:
  EXIT_INTRADAY_ORDERS_ON_STOP: true
  EXIT_TPLUS0_DELIVERY_ORDERS_ON_STOP: false
  EXIT_TPLUS1_DELIVERY_ORDERS_ON_STOP: false
  EXIT_TPLUS2_DELIVERY_ORDERS_ON_STOP: false
FUNDS:
  CREDIT_EXPOSURE_FACTOR: 1
  INITIAL_FUNDS_VIRTUAL: 1000000000
MISC:
  CROSSOVER_ACCURACY_DECIMALS: 2
  MAX_ORDERS_COUNT: 100
RESUME:
  AUTO_ADD_INSTRUMENTS_BUCKET_FROM_HOLDINGS_TPLUS1: false
  AUTO_ADD_INSTRUMENTS_BUCKET_FROM_HOLDINGS_TPLUS2: false
  AUTO_ADD_INSTRUMENTS_BUCKET_FROM_POSITIONS: false
  RESUME_HOLDINGS_TPLUS1_ON_START: false
  RESUME_HOLDINGS_TPLUS2_ON_START: false
  RESUME_POSITIONS_ON_START: false
RISK_MANAGEMENT:
  PNL_SCAN_FREQUENCY: 30
  PROFIT_DESIRED: null
  RISK_APPETITE: null
STRATEGY:
  INSTRUMENTS_BUCKET:
   - NSE_IDX:NIFTY BANK
  MODE: INTRADAY
  NAME: Strategy Options Long Iron Condor With Re-Entry
  NUMBER_OF_LOTS: 1
  PARAMETERS:
    NUMBER_OF_OTM_STRIKES_BUY_CALL_LEG: 1
    NUMBER_OF_OTM_STRIKES_SELL_CALL_LEG: 3
    NUMBER_OF_OTM_STRIKES_BUY_PUT_LEG: 1
    NUMBER_OF_OTM_STRIKES_SELL_PUT_LEG: 3
    ALLOW_REENTRY_UPPER: 1
    ALLOW_REENTRY_LOWER: 1
    RE_ENTRY_UPPER_LEVEL: 500
    RE_ENTRY_LOWER_LEVEL: 500
SYSTEM:
  TRADING_TYPE: BACKTESTING
  TRADING_START_TIME: 11-03-2023 09:15 +0530
  TRADING_END_TIME: 17-03-2023 15:15 +0530
  
