ABC:
  VERSION: 3.3.0
BROKING_DETAILS: { }
CANDLE:
  CANDLE_INTERVAL: 60minutes
EXIT:
  EXIT_INTRADAY_ORDERS_ON_STOP: true
  EXIT_TPLUS0_DELIVERY_ORDERS_ON_STOP: false
  EXIT_TPLUS1_DELIVERY_ORDERS_ON_STOP: false
  EXIT_TPLUS2_DELIVERY_ORDERS_ON_STOP: false
FUNDS:
  CREDIT_EXPOSURE_FACTOR: 1
  INITIAL_FUNDS_VIRTUAL: 1000000000
MISC:
  CROSSOVER_ACCURACY_DECIMALS: 2
  MAX_ORDERS_COUNT: 100
RESUME:
  AUTO_ADD_INSTRUMENTS_BUCKET_FROM_HOLDINGS_TPLUS1: false
  AUTO_ADD_INSTRUMENTS_BUCKET_FROM_HOLDINGS_TPLUS2: false
  AUTO_ADD_INSTRUMENTS_BUCKET_FROM_POSITIONS: false
  RESUME_HOLDINGS_TPLUS1_ON_START: false
  RESUME_HOLDINGS_TPLUS2_ON_START: false
  RESUME_POSITIONS_ON_START: false
RISK_MANAGEMENT:
  PNL_SCAN_FREQUENCY: 30
  PROFIT_DESIRED: null
  RISK_APPETITE: null
  RATE_LIMIT_MAX_ORDER_CALLS: 10
  RATE_LIMIT_WINDOW_TIME_SECONDS: 1
STRATEGY:
  INSTRUMENTS_BUCKET:
    - NSE_IDX:NIFTY 50
  MODE: INTRADAY
  NAME: Strategy Options Short Call Butterfly With Price Exit and Re-Entry
  NUMBER_OF_LOTS: 1
  PARAMETERS:
    NUMBER_OF_OTM_STRIKES_BUY_CALL_LEG: 1
    NUMBER_OF_ITM_STRIKES_BUY_CALL_LEG: 1
    ALLOW_UPPER_PRICE_BREACH: 1
    ALLOW_LOWER_PRICE_BREACH: 1
    PRICE_BREACH_UPPER_OFFSET: 500
    PRICE_BREACH_LOWER_OFFSET: 500
    TARGET_PERCENTAGE: 20
    STOPLOSS_PERCENTAGE: 10
    REENTRY_LIMIT: 1
SYSTEM:
  TRADING_TYPE: BACKTESTING
  TRADING_START_TIME: 11-03-2023 09:15 +0530
  TRADING_END_TIME: 17-03-2023 15:15 +0530
